name: Run SHiFT Bot (daily)

on:
  schedule:
    - cron: "0 0 * * *"   # Run every day at 00:00 UTC (6 PM Denver during DST, 5 PM during Standard Time)
  workflow_dispatch:        # Allows manual runs from the Actions tab

permissions:
  contents: read            # No need to write to repo since we aren't committing files

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout your code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Run the bot
      - name: Run bot
        env:
          DB_PATH: ./shift_codes.db
          HTML_SOURCES: ${{ secrets.HTML_SOURCES }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_SUBS: ${{ secrets.REDDIT_SUBS }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: python main.py

      # 5) Upload the database as a GitHub artifact instead of committing
      - name: Upload shift_codes.db as artifact
        uses: actions/upload-artifact@v4
        with:
          name: shift_codes-database
          path: shift_codes.db
          retention-days: 30  # Keep the DB for 30 days (you can increase if needed)
