name: Run SHiFT Bot (daily)

on:
  schedule:
    - cron: "0 0 * * *"   # Run every day at 00:00 UTC (6 PM Denver during DST, 5 PM during Standard Time)
  workflow_dispatch:        # Allows manual runs from the Actions tab

permissions:
  contents: read            # We no longer need write permissions

jobs:
  run:
    runs-on: ubuntu-latest
    steps:
      # 1) Checkout code
      - name: Checkout
        uses: actions/checkout@v4

      # 2) Set up Python
      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      # 3) Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4) Download the most recent DB artifact if one exists
      - name: Download latest shift_codes.db artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: run.yml          # Name of this workflow file
          name: shift_codes-database  # The artifact name
          path: ./                    # Download it to the repo root
          if_no_artifact_found: ignore

      # 5) Run the bot using the latest DB
      - name: Run bot
        env:
          DB_PATH: ./shift_codes.db
          HTML_SOURCES: ${{ secrets.HTML_SOURCES }}
          REDDIT_CLIENT_ID: ${{ secrets.REDDIT_CLIENT_ID }}
          REDDIT_CLIENT_SECRET: ${{ secrets.REDDIT_CLIENT_SECRET }}
          REDDIT_USER_AGENT: ${{ secrets.REDDIT_USER_AGENT }}
          REDDIT_SUBS: ${{ secrets.REDDIT_SUBS }}
          DISCORD_WEBHOOK_URL: ${{ secrets.DISCORD_WEBHOOK_URL }}
          SLACK_WEBHOOK_URL: ${{ secrets.SLACK_WEBHOOK_URL }}
        run: |
          # If there is no previous DB, create an empty file
          if [ ! -f shift_codes.db ]; then
            echo "No previous DB found, creating a new one."
            touch shift_codes.db
          fi
          python main.py

      # 6) Upload the updated DB as a new artifact
      - name: Upload updated shift_codes.db
        uses: actions/upload-artifact@v4
        with:
          name: shift_codes-database
          path: shift_codes.db
          retention-days: 30   # Artifacts kept for 30 days
